### ISSUE TITLE
Microsoft Edge Extension

### ISSUE THREAD

**Issue by thororen1234** [Chaython/EquicordPlus#1]
### Content

Hello, I'm the main dev for Equicord and I was looking into finally publishing a Microsoft Edge extension would it be okay if you joined our discord server to discuss this further as you own the current extension under Equicord Web.

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Chaython** [comment]
> ### Content
> Hello, I'm the main dev for Equicord and I was looking into finally publishing a Microsoft Edge extension would it be okay if you joined our discord server to discuss this further as you own the current extension under Equicord Web.
> 
> ### Request Agreement
> * [x]  I have read the requirements for opening an issue above

I never saw this before sorry, I had joined the equicord discord server before and talked about edge publishing and someone jsut told me no plans to or whatever which is why I forked and published it

**Comment by Chaython** [comment]
I also believe there wasn't even a chromium build because when I first used the plugin, you guys also said there wasn't the ability to buildWeb like in vencord, I explained you could... they said it wasn't officially supported.
They rejected my commit to include the following plugin before you guys made a native implementation a year later...

**Comment by thororen1234** [comment]
> I also believe there wasn't even a chromium build because when I first used the plugin, you guys also said there wasn't the ability to buildWeb like in vencord, I explained you could... they said it wasn't officially supported. They rejected my commit to include the following plugin before you guys made a native implementation a year later...

yes... Chrome firefox and edge just randomly approved us after a year of trying I couldnt tell you lol also what commit are you talking about I couldnt find anything in our server

**Comment by thororen1234** [comment]
@Chaython
